import VMdijs from 'vue-mdijs';
import {
  mdiFormatBold,
  mdiFormatItalic,
  mdiFormatStrikethrough,
  mdiFormatUnderline,
  mdiFormatAlignCenter,
  mdiFormatAlignLeft,
  mdiFormatAlignRight,
  mdiChevronDown,
  mdiFormatListNumbered,
  mdiFormatListBulleted,
  mdiLinkVariant,
  mdiImageOutline,
  mdiFormatQuoteCloseOutline,
  mdiGreasePencil,
  mdiLinkVariantRemove,
  mdiImageFilterCenterFocusWeak,
  mdiFolderOpenOutline,
  mdiCodeTags,
  mdiFileTreeOutline,
  mdiFormatHeader1,
  mdiFormatHeader2,
  mdiFormatHeader3,
  mdiFormatParagraph,
  mdiXml,
} from '@mdi/js';

VMdijs.add({
  mdiFormatBold,
  mdiFormatItalic,
  mdiFormatStrikethrough,
  mdiFormatUnderline,
  mdiFormatAlignCenter,
  mdiFormatAlignLeft,
  mdiFormatAlignRight,
  mdiChevronDown,
  mdiFormatListNumbered,
  mdiFormatListBulleted,
  mdiLinkVariant,
  mdiImageOutline,
  mdiFormatQuoteCloseOutline,
  mdiGreasePencil,
  mdiLinkVariantRemove,
  mdiImageFilterCenterFocusWeak,
  mdiFolderOpenOutline,
  mdiCodeTags,
  mdiFileTreeOutline,
  mdiFormatHeader1,
  mdiFormatHeader2,
  mdiFormatHeader3,
  mdiFormatParagraph,
  mdiXml,
});

export default VMdijs;
